// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzkwzkzzemzqdtquzagl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6a3d6a3p6ZW16cWR0cXV6YWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTYyOTAsImV4cCI6MjA2MjY5MjI5MH0.Qor-4Bv_oZnCZ2kuonCDTGR4NRDVsKQrgZoileh4vA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);